config/routes.rb
Rails.application.routes.draw do
  # resources :airlines
  # resources :hotels
  # resources :clients
  resources :agents

  get "/login", to:"agents#login", as: "login"
  post "/handle_login", to: "agents#handle_login"
  delete "/logout", to:"agents#logout", as: "logout"

  get "/clients", to:"clients#index", as: "clients"
  get "/clients/new", to: "clients#new", as: "new_client"
  post "/clients", to: "clients#create"
  get "/clients/:id", to: "clients#show", as: "client"
  get "/clients/:id/edit", to: "clients#edit", as: "edit_client"
  patch "/clients/:id", to: "clients#update"
  delete "/clients/:id", to: "clients#destroy"

  get "/hotels", to: "hotels#index", as: "hotels"

  get "/airlines", to: "airlines#index", as: "airlines"

  get "/vacations/new", to: "vacations#new", as: "new_vacation"
  post "/vacations", to: "vacations#create"
  get "vacations/:id", to:"vacations#show", as: "vacation"
  get "/vacations/:id/edit", to: "vacations#edit", as: "edit_vacation"
  patch "/vacations/:id", to: "vacations#update"

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
class Agent < ApplicationRecord
    has_many :clients 
    has_secure_password

    def reach_bonus
        if self.clients.size >= 6
            "*Congratulations on reaching your client portfolio target! Contact HR for reward incentives!*"
        end
    end
end

app/models/airline.rb
class Airline < ApplicationRecord
    has_many :vacations 
    has_many :hotels, through: :vacations
    has_many :clients, through: :vacations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :agent
  has_many :vacations, dependent: :destroy
  has_many :hotels, through: :vacations
  has_many :airlines, through: :vacations

  def is_senior
    if self.age >= 65
      return true
    end
  end

  def premiere_customer
    if self.vacations.size >= 5
      "*This client is a premiere customer*"
    end
  end
end
 

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :vacations
    has_many :airlines, through: :vacations
    has_many :clients, through: :vacations
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :airline
  belongs_to :client
  belongs_to :hotel

  def total_price
    self.hotel_price + self.airline_price
  end

  def discount
    # hotel_discount= self.hotel_price* 0.9
    # airline_discount= self.airline_price *0.9
    if self.client.is_senior
      self.hotel_price = self.hotel_price * 0.9
      self.airline_price= self.airline_price * 0.9
      return true
    end
  end

  
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
    skip_before_action :authorize, only:[:login, :handle_login, :new, :create]
    
    def new 
        @agent = Agent.new
    end

    def create
        @agent = Agent.create(agent_params)
        session[:agent_id] = @agent.id
        redirect_to login_path
    end

    def login 
    end

    def handle_login
        @agent = Agent.find_by(username: params[:username])
        if @agent && @agent.authenticate(params[:password])
            session[:agent_id] = @agent.id
            redirect_to clients_path
        else
            flash[:errors]=["Incorrect username or password"]
            redirect_to login_path
        end
    end

    def logout
        logout_agent 
        redirect_to login_path
    end 

    private
    def agent_params
        params.require(:agent).permit(:name, :username, :password)
    end
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
    def index
        @airlines = Airline.all 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_agent, :is_logged_in?
    before_action :authorize

    def current_agent
        @current_agent = Agent.find_by(id: session[:agent_id])
    end

    def is_logged_in?
        !!current_agent
    end

    def authorize
        unless is_logged_in?
            redirect_to login_path
        end
    end

    def logout_agent
        session[:agent_id] = nil
        end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

    def index
        @clients = Client.all
    end

    def new
    
        @client= Client.new
    end

    def show
        @client= Client.find(params[:id])
    end

    def create 
        @client= @current_agent.clients.create(client_params)
        redirect_to client_path (@client)
    end

    def edit
        @client = Client.find(params[:id])
    end

    def update
        @client = Client.find(params[:id])
        @client.update(client_params)
        redirect_to client_path(@client)
    end

    def destroy
        @client = Client.find(params[:id])
        @client.destroy
        redirect_to clients_path
    end


    private
    def client_params
    params.require(:client).permit(:name, :age)
    end


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
def index
    @hotels = Hotel.all
end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
   def new
    @vacation = Vacation.new
   end

   def create
      @vacation = Vacation.create(vacation_params)
      redirect_to vacation_path(@vacation)
   end

   def show
      @vacation = Vacation.find(params[:id])
   end

   def edit
      @vacation = Vacation.find(params[:id])
   end

   def update
      @vacation = Vacation.find(params[:id])
      @vacation.update(vacation_params)
      redirect_to vacation_path(@vacation)
   end



   private

   def vacation_params
      params.require(:vacation).permit(:date, :destination, :hotel_price, :airline_price, :airline_id, :hotel_id, :client_id)
   end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/agents/login.html.erb
<%if flash[:errors]%>
<%flash[:errors].each do |message|%>
<p><b><%=message%></b></p>
<%end%>
<%end%>


<%= form_tag "/handle_login" do%>
<%= label_tag :username, "Enter your username"%>
<%= text_field_tag :username%>
<%= label_tag :password, "Enter your password"%>
<%= password_field_tag :password%>
<%= submit_tag "Login"%>
<%end%>
<%= button_to "Signup", new_agent_path, method: "get"%>

app/views/agents/new.html.erb
<h1> Create your Agent Login </h1>

<%= form_for @agent do |f| %>
    <%=f.label :name %>
    <%=f.text_field :name%>
    <%= f.label :username %>
    <%=f.text_field :username %>
    <%=f.label :password %>
    <%=f.password_field :password %>
    <%= f.submit %>
    <% end %>

    <%= button_to "Back", login_path, method: "get"%>

app/views/airlines/index.html.erb
<h1> All Airlines </h1>

<p> <strong> Airline:</strong> <a href="https://www.delta.com/"> <%= @airlines[0].name%>  </p> </a> 
<p> <strong> Airline:</strong>  <a href="https://www.aa.com/homePage.do"> <%= @airlines[1].name%>  </p> </a>
<p> <strong> Airline:</strong>  <a href="https://www.jetblue.com/"><%= @airlines[2].name%>  </p> </a>
<p> <strong> Airline:</strong>  <a href="https://www.spirit.com/"> <%= @airlines[3].name%> </p> </a>
<p> <strong> Airline:</strong>  <a href="https://www.united.com/en/us"><%= @airlines[4].name%> </p> </a>
<p> <strong> Airline:</strong>  <a href="https://www.southwest.com/"> <%= @airlines[5].name%> </p> </a>
<p> <strong> Airline:</strong>  <a href="https://www.flyfrontier.com/"><%= @airlines[6].name%> </p> </a>
<p> <strong> Airline:</strong>  <a href="https://www.virginatlantic.com/us/en"><%= @airlines[7].name%> </p> </a>
   
<%=button_to "Back" , clients_path, method: "get"%>
<%= button_to "Logout", logout_path, method: "delete"%> 

app/views/clients/edit.html.erb
<h1> Edit a client </h1>

 <%= form_for @client do |f| %>
    <%= f.label :name %>
    <%=f.text_field :name %>
    <%=f.label :age %>
    <%=f.number_field :age %>
    <%= f.submit %> 
    <% end %>
<p>

</p>
<%=button_to "Back to client", client_path(@client), method: 'get' %>
<%= button_to "Logout", logout_path, method: "delete"%> 

app/views/clients/index.html.erb
<h1> All Clients </h1>
<p><b><%= current_agent.reach_bonus%></b></p>

<ul>


<% @clients.each do |client| %>
<%if current_agent.id == client.agent_id%>
   <li>
    <p> <strong> Name: <%= link_to client.name, client_path(client) %> </strong> </p>
  </li>
    <%end%>
    <%end%>
   

   </ul>
<%=button_to "Add Client" , new_client_path, method: "get"%>       
<%=button_to "Find Flight" , airlines_path, method: "get"%> 
<%=button_to "Find Hotel" , hotels_path, method: "get"%> 
<%= button_to "Logout", logout_path, method: "delete"%> 

app/views/clients/new.html.erb
<h1> Create a new client </h1>

    <%= form_for @client do |f| %>
    <%= f.label :name %>
    <%=f.text_field :name %>
    <%=f.label :age %>
    <%=f.number_field :age %>
    <%= f.submit %>
    <% end %>
    <%= button_to "Logout", logout_path, method: "delete"%> 
    <%=button_to "Back" , clients_path, method: "get"%>
    

app/views/clients/show.html.erb
<h1> Client Info </h1>

<p><b><%= @client.premiere_customer%></b></p>
<p><b>Name</b> - <%= @client.name%></p>
<p><b>Age</b> - <%= @client.age%></p>

<%=button_to "Edit Client", edit_client_path, method: 'get' %>
<%= button_to "Delete Client","/clients/#{@client.id}", method: 'delete' %>


<h1> List of vacations </h1>

<% @client.vacations.each do |vacation| %>
<li>
<%= link_to vacation.destination, vacation_path(vacation.id)%> - <%= vacation.date %>
</li>
<% end %>

<%=button_to "Back to client list", clients_path, method: 'get' %>
<%=button_to "Create Vacation", new_vacation_path, method: 'get'%>
<%= button_to "Logout", logout_path, method: "delete"%> 

app/views/hotels/index.html.erb
<h1> List of Hotels </h2>

<p> <strong> Name:</strong>  <a href= "https://www.marriott.com/default.mi"> <%= @hotels[0].name%> </p> </a> 
<p> <strong> Name:</strong>  <a href= "https://www.hilton.com/en/"> <%= @hotels[1].name%> </p> </a> 
<p> <strong> Name:</strong> <a href= "https://www.wyndhamhotels.com/ramada"> <%= @hotels[2].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.trumphotels.com/"> <%= @hotels[3].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.fourseasons.com/"> <%= @hotels[4].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.choicehotels.com/quality-inn"><%= @hotels[5].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.wyndhamhotels.com/super-8"> <%= @hotels[6].name%> </p> </a>
<p> <strong> Name:</strong> <a href= "https://www.hilton.com/en/doubletree/"> <%= @hotels[7].name%> </p> </a>
<p> <strong> Name:</strong> <a href= "https://www.caesars.com/ballys-las-vegas"> <%= @hotels[8].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.hardrockhotels.com/"><%= @hotels[9].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.ritzcarlton.com/"><%= @hotels[10].name%> </p> </a>
<p> <strong> Name:</strong>  <a href= "https://www.caesars.com/caesars-palace/hotel"><%= @hotels[11].name%> </p> </a>

  
<%=button_to "Back" , clients_path, method: "get"%>
<%= button_to "Logout", logout_path, method: "delete"%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransparenTravel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <h1 align='center' style='font-size:4rem;color:#3346FF'>Transparent Travel</h1>
    <%= yield %>
  </body>
</html>

app/views/vacations/edit.html.erb
<h1> Edit a vacation </h1>

  <%= form_for @vacation do |f| %>
  <%=f.label :client_id %>
    <%=f.collection_select :client_id, Client.all, :id, :name %>
    <%=f.label :hotel_id %>
    <%=f.collection_select :hotel_id, Hotel.all, :id, :name %>
    <%=f.label :airline_id %>
    <%= f.collection_select :airline_id, Airline.all, :id, :name%>
    <%= f.label :date%>
    <%=f.text_field :date %>
    <%= f.label :destination%>
    <%=f.text_field :destination %>
    <%= f.label :airline_price%>
    <%= f.number_field :airline_price, :step => 0.01%>
    <%= f.label :hotel_price%>
    <%= f.number_field :hotel_price, :step => 0.01 %>
    <%= f.submit%>
    <% end %>

    <%=button_to "Back ", vacation_path(@vacation), method: 'get' %>
<%= button_to "Logout", logout_path, method: "delete"%> 

app/views/vacations/new.html.erb
<h1> Create a new vacation </h1>

  <%= form_for @vacation do |f| %>
   <%=f.label :client_id %>
    <%=f.collection_select :client_id, Client.all, :id, :name %>
    <%=f.label :hotel_id %>
    <%=f.collection_select :hotel_id, Hotel.all, :id, :name %>
    <%=f.label :airline_id %>
    <%= f.collection_select :airline_id, Airline.all, :id, :name%>
    <%= f.label :date%>
    <%=f.text_field :date %>
    <%= f.label :destination%>
    <%=f.text_field :destination %>
    <%= f.label :airline_price%>
  <%= f.number_field :airline_price, :step => 0.01 %>
   <%= f.label :hotel_price%>
    <%= f.number_field :hotel_price, :step => 0.01 %>
    <%= f.submit%>
    <% end %>
    <%=button_to "Back to clients", clients_path, method: 'get' %>
    <%= button_to "Logout", logout_path, method: "delete"%> 

app/views/vacations/show.html.erb
<h1> Vacation Information </h1>
<%@vacation.discount%>
<p> Destination: <%= @vacation.destination %></p>
<p> Date: <%= @vacation.date %> </p>
<p> Hotel: <%= @vacation.hotel.name %> - $<%= @vacation.hotel_price %></p>
<p> Airline: <%= @vacation.airline.name %> - $<%= @vacation.airline_price %></p>
<p> Total Price: $<%= @vacation.total_price %>
<p><b>ALL CLIENTS ABOVE THE AGE OF 65 RECIEVE A 10% DISCOUNT ON TOTALPRICE!</b><p>

<%= button_to "Edit vacation", edit_vacation_path(@vacation), method: 'get' %>
<%=button_to "Back to client", client_path(@vacation.client_id), method: 'get' %>
<%= button_to "Logout", logout_path, method: "delete"%> 